development:
  adapter: postgresql
  encoding: unicode
  database: octopi_development
  pool: 5
  username: octopi
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: octopi_test
  pool: 5
  username: octopi
  password:

cucumber:
  <<: *test
